version: '3.1'
services:
  web:
    container_name: ${ODOO_CONTAINER_NAME}
    image: devodoo:${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:${ODOO_PORT}"
      - "${DEBUGPY_PORT}:${DEBUGPY_PORT}"
    environment:
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ${ODOO_SERVER}:/var/lib/odoo/odoo
      - ${CUSTOM_ADDONS}:/var/lib/odoo/custom_addons
    entrypoint: ${ENTRYPOINT}
  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdb-data:/var/lib/postgresql/data/pgdata                  
volumes:
  odoo-web-data:
  pgdb-data:

